// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEWkM7gZKU1WWR75JisIl--vzq7dB9Iac',
    appId: '1:759711685477:android:7381277483c0e18fdfdf8c',
    messagingSenderId: '759711685477',
    projectId: 'akiramenai-76343',
    storageBucket: 'akiramenai-76343.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS7TlaY4RM6xdk3jcJYH07ybjEeUnpghw',
    appId: '1:759711685477:ios:66266a458c4f7eacdfdf8c',
    messagingSenderId: '759711685477',
    projectId: 'akiramenai-76343',
    storageBucket: 'akiramenai-76343.firebasestorage.app',
    androidClientId: '759711685477-a9v9k4c43ujqkmk81uvoqhmlhl5ou6gq.apps.googleusercontent.com',
    iosClientId: '759711685477-jgmat5su4vuidhf7nt664tkdricg1fkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.Temply',
  );

}